export const ACTION_TYPES = {
  _AMOUNT: "_AMOUNT",
  _SUBJECT: "_SUBJECT",
  _LANGUAGE: "_LANGUAGE",
  _SUBMIT_SEARCH: "_SUBMIT_SEARCH",
  _SUCCESSFUL_SEARCH: "_SUCCESSFUL_SEARCH",
  _FAILED_SEARCH: "_FAILED_SEARCH",
  _FRONT_PAGE_SEARCH: "_FRONT_PAGE_SEARCH",
  _TOGGLE_SEARCH_FORM: "_TOGGLE_SEARCH_FORM",
};
